#!/bin/bash

function filter_file() {
	local File=$1
	local Pattern=$2
	
	cat $File | grep $Pattern > ${File}_$Pattern
}

function filter_addr() {
	local File=$1
	
	cat $File | awk '{print $3}' | sort > ${File}.addrs
}

cat ./test.log | grep CREATE > ./test.create
cat ./test.log | grep DELETE > ./test.delete

filter_file ./test.create ITask
filter_file ./test.delete ITask

filter_file ./test.create KPSR
filter_file ./test.delete KPSR

filter_file ./test.create KPST
filter_file ./test.delete KPST

filter_addr ./test.create
filter_addr ./test.delete


filter_addr ./test.create_ITask
filter_addr ./test.delete_ITask

filter_addr ./test.create_KPST
filter_addr ./test.delete_KPST

filter_addr ./test.create_KPSR
filter_addr ./test.delete_KPSR




